<div class='tacSection'>

    <div class='tacOverlay tacClose'></div>
    <div class='tacContainer '>
        <div class='container'>
            <div class='containerCloseBtn tacClose'><i class='ti ti-close'></i> </div>
            <h1 class='title'> Terms & Conditions </h1>
            <div class='tac-content'>
                <div class='row'>
                    <div class='col-12'>
                        <p>In using this website you are deemed to have read and agreed to the following terms and conditions:  </p>
                        <p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and any or all Agreements: "Client", “You” and “Your” refers to you, the person accessing this website and accepting the Company’s terms and conditions. "The Company", “Ourselves”, “We” and "Us", refers to CLOUDSITE SOLUTION. “Party”, “Parties”, or “Us”, refers to both the Client and ourselves, or either the Client or ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner, whether by formal meetings of a fixed duration, or any other means, for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services/products, in accordance with and subject to, prevailing Malaysia Law. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.  </p>
                        <p>1. Privacy Statement We are committed to protecting your privacy. Authorized employees within the company on a need to know basis only use any information collected from individual customers. We constantly review our systems and data to ensure the best possible service to our customers. Parliament has created specific offences for unauthorised actions against computer systems and data. We will investigate any such actions with a view to prosecuting and/or taking civil proceedings to recover damages against those responsible  </p>
                        <p>2. Confidentiality We are registered under the Data Protection Act 1998 and as such, any information concerning the Client and their respective Client Records may be passed to third parties. However, Client records are regarded as confidential and therefore will not be divulged to any third party, other than [our manufacturer/supplier(s) and] if legally required to do so to the appropriate authorities.  </p>
                        <p>We will not sell, share, or rent your personal information to any third party or use your e-mail address for unsolicited mail. Any emails sent by this Company will only be in connection with the provision of agreed services and products.  </p>

                        <h1>Disclaimer  </h1>
                        <p>1. Exclusions and Limitations The information on this website is provided on an "as is" basis. To the fullest extent permitted by law, this Company: excludes all representations relating to this website and its contents or which is or may be provided by any affiliates or any other third party, including in relation to any inaccuracies or omissions in this website and/or the Company’s literature; and excludes all liability for health issue, death, sickness and/or other health concern after usage of purchased from this website. Any problem occurred we strongly advise person in charge to consult health physician and/or vets.  </p>
                        <p>2. Payment 2.1 The Buyer shall be entitled to make payment for the Goods pursuant to the various payment methods set out in CLOUDSITE SOLUTION’s website. The terms and conditions applicable to each type of payment, as contained in CLOUDSITE SOLUTION’s website, shall be applicable to the Contract. 2.2 In addition to any additional terms contained in CLOUDSITE SOLUTION’s website, the following terms shall also apply to the following types of payment: 2.2.1 Credit Card Credit Card payment option is available for all Buyers. CLOUDSITE SOLUTION accepts all Visa and MasterCards, both Credit and Debit, and is 3D Secure (Verified by Visa, and MasterCard Secure) enabled. All your credit card information are protected by means of industry- leading encryption standards. Please take note that additional charges may be incurred if you are using a non-Malaysian issues card due to Foreign Exchange. 2.2.2 Debit Cards CLOUDSITE SOLUTION accepts all Malaysian Visa and MasterCard debit cards where subject to bank availability. All debit card numbers shall be protected by means of industry-leading encryption standards. 2.2.3 Online Banking i. By choosing this payment method, the Buyer shall transfer the payment for the Goods to a CLOUDSITE SOLUTION’s account for the total amount of the Buyer’s purchase (including any applicable taxes, fees and shipping costs). The transaction must be payable in Ringgit Malaysia. CLOUDSITE SOLUTION, in its sole discretion, may refuse this payment option service to anyone or any user without notice for any reason at any time. ii. For the time being, CLOUDSITE SOLUTION accepts online bank transfers from AmBank, Bank Islam, CIMB Bank, Hong Leong, Maybank, Public Bank, RHB and any other local bank. 2.2.4 Cash On Delivery Cash on Delivery (Pay cash upon delivery) is only available for FIRST TIME ORDER within the region of Klang Valley by request. The Goods will only be handed over to the Buyer upon full payment in cash by the Buyer. 2.3 If the Buyer fails to make any payment pursuant to the terms and conditions of the payment method elected, then without prejudice to any other right or remedy available to CLOUDSITE SOLUTION, CLOUDSITE SOLUTION shall be entitled to: 2.3.1 cancel or suspend deliveries of the Goods until payment is made in full.  </p>
                        <p>3. Cancellation Policy Minimum 24 hours notice of order cancellation is required. Paid services, shipped & paid orders are not cancellable. Notification for instance, in person, mobile phone ‘text message’, or any other means will be accepted subject to confirmation in writing. We reserve the right to reject cancellation of special-order product that cannot be returned.  </p>
                        <p>4. User Comments, Feedback and Other Submissions If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments.  </p>
                        <p>We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.  </p>
                        <p>You agree that your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You may not use a false e-mail address, or social media account pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party.  </p>
                        <p>5. Personal Information Your submission of personal information through the store is governed by our Privacy Policy. To view our Privacy Policy.  </p>
                        <p>6. General The laws of Malaysia govern these terms and conditions. By accessing this website [and using our services/buying our products] you consent to these terms and conditions and to the exclusive jurisdiction of the Malaysia courts in all disputes arising out of such access. If any of these terms are deemed invalid or unenforceable for any reason (including, but not limited to the exclusions and limitations set out above), then the invalid or unenforceable provision will be severed from these terms and the remaining terms will continue to apply. Failure of the Company to enforce any of the provisions set out in these Terms and Conditions and any Agreement, or failure to exercise any option to terminate, shall not be construed as waiver of such provisions and shall not affect the validity of these Terms and Conditions or of any Agreement or any part thereof, or the right thereafter to enforce each and every provision. These Terms and Conditions shall not be amended, modified, varied or supplemented except in writing and signed by duly authorized representatives of the Company.  </p>
                        <p>7. Notification of Changes The Company reserves the right to change these conditions from time to time as it sees fit and your continued use of the site will signify your acceptance of any adjustment to these terms. If there are any changes to our privacy policy, we will announce that these changes have been made on our home page and on other key pages on our site. If there are any changes in how we use our site customers’ Personally Identifiable Information, notification by e-mail or postal mail will be made to those affected by this change. Any changes to our privacy policy will be posted on our website 30 days prior to these changes taking place. You are therefore advised to re-read this statement on a regular basis  </p>
                        <p>8. Warranty Goods sold are bind with 30 days warranty, if and only if the goods sold are proven damaged/ with defect/ with poor quality within 30 days of period time. If such proofs are justified, CLOUDSITE SOLUTION may, but have no obligation to replace the specific goods.  </p>

                    </div>
                   
                </div>
            </div>
        </div>
    </div>
</div>
</div>